repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.272'
    hooks:
      - id: ruff
        args: ["--fix", "--ignore=E722", "--ignore=F401"]
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black